### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by avr248** [UKPLab/emnlp2017-relation-extraction#1]
1. After I finished training - how do I create a visual graph?
2. The demo does not work

Thank you very much

**Comment by daniilsorokin** [comment]
Hi, 

What do you mean by the visual graph? 

The demo should be working now. It froze, thanks you.

Best,
Daniil

**Comment by avr248** [comment]
after train i run applay_model.py:

File "apply-model.py", line 47, in <module>
    with open(data_folder + "properties-with-labels.txt") as infile:
FileNotFoundError: [Errno 2] No such file or directory: './data/properties-with-labels.txt'

**Comment by daniilsorokin** [comment]
Hi, sorry, the file was missing in the repository. I have added it in the latest commit.

**Comment by avr248** [comment]
Thanks for your help, and thank you for the code

**Comment by avr248** [comment]
Could you please upload a code to activate the server?

**Comment by daniilsorokin** [comment]
Hi, I've pushed the code to start the server. It is a FLASK application, you can read more about running a FLASK server here: http://flask.pocoo.org/docs/0.12/quickstart/#a-minimal-application

It needs a stanford corenlp server to function, see here: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

Please note, that the server is meant for demo purposes only and probably won't work very well under heavy load.

**Comment by avr248** [comment]
Thank you very much!!

**Comment by daniilsorokin** [comment]
Feel free to re-open the issue if you have further questions.
