### ISSUE TITLE
how many times on earth should we repeat the input?

### ISSUE THREAD

**Issue by FrankHui** [UKPLab/emnlp2017-relation-extraction#10]
line 284 in keras_model.py
```PYTHON
MAX_EDGES_PER_GRAPH = 7
```
line 97-98 & line 153-154
```PYTHON
# Repeat the input 3 times as will need it once for the target entity pair and twice for the ghost pairs
x = layers.RepeatVector(MAX_EDGES_PER_GRAPH)(sentence_input)
```

**Comment by daniilsorokin** [comment]
Hi,

the constant variable is correct, so the sentence input is repeated 7 times: one time for each entity pair (relation) in the sentence. The model can process up to 7 entity pairs (relations) per input and if there is more than 7, it splits the relations into multiple sets and processes them independently. 

Please, ignore the comment in the code, it refers to some older experiments that we did with the same model.
