### ISSUE TITLE
method

### ISSUE THREAD

**Issue by zxs1995** [UKPLab/emnlp2017-relation-extraction#13]
may I ask you if your method is a part of distant supervise, thank you

**Comment by daniilsorokin** [comment]
Yes, it is. See Section 3. in the paper: http://aclweb.org/anthology/D17-1188

**Comment by daniilsorokin** [comment]
Hi, the model was learned completely distantly supervised. Does it answer your question?

**Comment by zxs1995** [comment]
You have solved my question. Thank you very much.
