### ISSUE TITLE
Notebook corrupt

### ISSUE THREAD

**Issue by ArunAniyan** [UKPLab/emnlp2017-relation-extraction#18]
When I try to load the ipython notebook, I get this strange error.

NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

I see you uploaded a new notebook 2 months ago. Anything with the versioning ?

**Comment by daniilsorokin** [comment]
Hi,

thank you for flagging this. Please try again with the latest version.

Best
Daniil

**Comment by ArunAniyan** [comment]
Thanks! Seems to be working :)

Cheers,
Arun
