### ISSUE TITLE
parsed_graph runs into error

### ISSUE THREAD

**Issue by ArunAniyan** [UKPLab/emnlp2017-relation-extraction#19]
Hi,

I just started running the recent version of the notebook and it crashes at the step where the keras model is used to get the parsed graph.
Please see the attached screenshot

![image](https://user-images.githubusercontent.com/5010454/56710757-489a8000-6745-11e9-87fa-119bccef84d5.png)

Any help to fix this would be really appreciated.

Thanks,
Arun

**Comment by daniilsorokin** [comment]
Oh, sorry, this is a typo. Fixed it, please try the update version.

**Comment by ArunAniyan** [comment]
Works perfect !

Thanks a lot !
