### ISSUE TITLE
About how to run your pretained models

### ISSUE THREAD

**Issue by ProKil** [UKPLab/emnlp2017-relation-extraction#2]
I'm wondering how to run your pretrained models. I've tried `python model-train-and-test.py model_ContextWeighted`, but it shows up that `AttributeError: 'module' object has no attribute 'model_ContextWeighted'`. 
Could you provide some basic usage instruction?

Really appreciate your work, thank you!

**Comment by daniilsorokin** [comment]
Hi, 
thank you for the reporting, there sort of a bug in there. The model names in the description and in the code are different, because of some last time changes. I will try to fix it in the upcoming days. 

Meanwhile, it should work if you use "model_RnnMarkersScoredGhosts" instead of "model_ContextWeighted". Don't forget to set the rest of the command line parameters when calling `python model-train-and-test.py `. See here: https://github.com/UKPLab/emnlp2017-relation-extraction/blob/4c789802690f37f4e5c7dd6da6b1397d67da52c6/relation_extraction/model-train-and-test.py#L69

Best,
Daniil

**Comment by ProKil** [comment]
Thank you for your response. 

I changed "model_ContextWeighted.(kerasmodel/property2idx)" to "model_RnnMarkersScoredGhosts.(kerasmodel/property2idx)" and called `python model-train-and-test.py --mode test model_RnnMarkersScoredGhosts`, which also caused an error "TypeError: arg 5 (closure) must be None or tuple" while loading the model at line 198 of "model-train-and-test.py". 

Did I make some mistakes on the parameters? 

Best,
Hao

**Comment by daniilsorokin** [comment]
Hi,
that is a bug in model loading that has something to do with the Keras `load_model` method. There is a workaround, I have pushed a commit that fixes it.
Best, Daniil

**Comment by ProKil** [comment]
Thank you. However, while testing another error, "ValueError: cannot reshape array of size 634368 into shape (7,46)" turns out on https://github.com/UKPLab/emnlp2017-relation-extraction/blob/4c789802690f37f4e5c7dd6da6b1397d67da52c6/relation_extraction/model-train-and-test.py#L45
while testing on the training set.

Other information:
"ValueError: cannot reshape array of size 634368 into shape (7,46)
Apply node that caused the error: Reshape{3}(SoftmaxWithBias.0, TensorConstant{[-1  7 46]})
Toposort index: 159
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector)]
Inputs shapes: [(1792, 354), (3,)]
Inputs strides: [(1416, 4), (8,)]
Inputs values: ['not shown', array([-1,  7, 46])]
Outputs clients: [['output']]"

Best,
Hao

**Comment by daniilsorokin** [comment]
I will have to take time to look into it. When does the error occur? I can't seem to reproduce it. Can you post the complete output in the command line?

**Comment by ProKil** [comment]
Traceback (most recent call last):
  File "model-train-and-test.py", line 204, in <module>
    evaluate(model, train_as_indices[:-1], train_as_indices[-1])
  File "model-train-and-test.py", line 49, in evaluate
    predictions = model.predict(input, batch_size=256, verbose=1)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/engine/training.py", line 1272, in predict
    batch_size=batch_size, verbose=verbose)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/engine/training.py", line 945, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/backend/theano_backend.py", line 959, in __call__
    return self.function(*inputs)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/zhuhao/py34/lib/python3.4/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: cannot reshape array of size 634368 into shape (7,46)
Apply node that caused the error: Reshape{3}(SoftmaxWithBias.0, TensorConstant{[-1  7 46]})
Toposort index: 159
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector)]
Inputs shapes: [(1792, 354), (3,)]
Inputs strides: [(1416, 4), (8,)]
Inputs values: ['not shown', array([-1,  7, 46])]
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "model-train-and-test.py", line 200, in <module>
    model = load_the_model(model_name, model_params, embeddings, max_sent_len, n_out)
  File "model-train-and-test.py", line 73, in load_the_model
    model = getattr(sp_models, model_name)(model_params, embeddings, max_sent_len, n_out)
  File "/data/disk3/private/zhuhao/emnlp2017-relation-extraction/relation_extraction/parsing/sp_models.py", line 491, in model_RnnMarkersScoredGhosts
    main_output = layers.wrappers.TimeDistributed(layers.Dense(n_out, activation = "softmax", name='main_output'))(edge_vectors)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/layers/wrappers.py", line 129, in call
    y = K.reshape(y, (-1, input_length) + output_shape[2:])
  File "/home/zhuhao/py34/lib/python3.4/site-packages/keras/backend/theano_backend.py", line 587, in reshape
    y = T.reshape(x, shape)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by daniilsorokin** [comment]
Did you set the THEANO flags? Are you trying on CPU or GPU?

For Theano flags try setting them to the following values: 
export THEANO_FLAGS=mode=FAST_RUN,device=cpu,floatX=float32

**Comment by ProKil** [comment]
It works after applying these flags. Thank you! 
Just wondering why you set the device to cpu?

**Comment by daniilsorokin** [comment]
I tested it on CPU now. If you want to run it on GPU it should work with device=gpu. Of course you need compatible hardware and CUDA drivers to run it on GPU.

**Comment by ProKil** [comment]
I found that "semantic-graphs-filtered-held-out.tagged.json" is needed, but not provided.

**Comment by daniilsorokin** [comment]
It is not needed if you want to reproduce the experiments from the paper. Please note that the code to compute the precision-recall graphs is not here, yet. 

I have fixed the script so that it doesn't ask for it.

**Comment by ProKil** [comment]
Hi, do you have the plan to publish your code to compute pr curve?

**Comment by daniilsorokin** [comment]
Yes, most probably next week.

**Comment by daniilsorokin** [comment]
Hi, unfortunately I couldn't prepare the code to generate the curves yet, but I posted some additional notes on replicating the experiments and added the raw data for the curves from the paper: [data/curves](https://github.com/UKPLab/emnlp2017-relation-extraction/tree/master/data/curves)

**Comment by daniilsorokin** [comment]
Hi, the code to compute the curves is now in the repo. See ReadMe
