### ISSUE TITLE
Question about the TimeDistributed

### ISSUE THREAD

**Issue by kangbrilliant** [UKPLab/emnlp2017-relation-extraction#20]
I'm little confused why do you not choose layers.wrappers.Bidirectional ?

**Comment by daniilsorokin** [comment]
We do, for instance https://github.com/UKPLab/emnlp2017-relation-extraction/blob/bed36b0fdf4dcfeeebf4c7e97b201b7cad1febba/relation_extraction/core/keras_models.py#L147

TimeDistributed is needed to process a bulk of relations from the same sentence. It is not used to distribute across time but rather across different relations in the sentence. It was just easier to implement that way.

**Comment by kangbrilliant** [comment]
@daniilsorokin  Thank you for your prompt answer，I‘m too careless. ☺
Another question, in the function :
`def get_entity_indexed_vector(tokens, edge, mode="mark-bi"):`
I don't quite understand that when mode is "mark-bi", when will the number 4 appear ?

**Comment by daniilsorokin** [comment]
4 as a token marker in the `mark-bi` was used for some new experiments that we did but were not used in the paper. The idea was to concatenate more than one sentence together and then mark with 4 the tokens in the adjacent sentences, but not the target sentence. It is turned off by default for the current models.
