### ISSUE TITLE
tensorflow backend work?

### ISSUE THREAD

**Issue by avr248** [UKPLab/emnlp2017-relation-extraction#4]

**Comment by daniilsorokin** [comment]
We haven't tested it yet, but it should theoretically work. We plan to update it to the latest Keras version + TensorFlow soon (probably in the next two weeks).

**Comment by avr248** [comment]
thank you

**Comment by daniilsorokin** [comment]
We tested it with TensorFlow and it should just work with the existing code. We will retrain the models and post them soon

**Comment by daniilsorokin** [comment]
We have switched to the TensorFlow backend now. The existing models work with the TensorFlow backend without re-training.
