### ISSUE TITLE
How to process the dataset?

### ISSUE THREAD

**Issue by monstertony** [UKPLab/emnlp2017-relation-extraction#5]
Hi,

Can I ask how can I process the dataset? I saw your training dataset is in a preprocessed format, can I ask how to preprocess those text?

Hope to get your reply! Thanks a lot in advance!!!

**Comment by daniilsorokin** [comment]
Th input dataset is in JSON format, so you can use any json serializer/deserializer to create/read it. What do you mean exactly by "preprocess"?

**Comment by monstertony** [comment]
Thanks for reply! I have checked your newest update. That using pre-trained nodels.ipynb is quite clear now.

**Comment by daniilsorokin** [comment]
Great to hear that!
