### ISSUE TITLE
CoreNLP version

### ISSUE THREAD

**Issue by andychisholm** [UKPLab/emnlp2017-relation-extraction#8]
Would be useful to have some documentation of the CoreNLP version/models used.

Pre-trained models seem to work much better with the previous CoreNLP release (3.8.0) in comparison with the current one (3.9.1).

**Comment by daniilsorokin** [comment]
Hi,

this is a good comment! Thanks you. 

I have used the CoreNLP 3.7.0 models, it is semi-documented in the code :)
https://github.com/UKPLab/emnlp2017-relation-extraction/blob/f3a6159bd1c424fffb467723b4b0abaab4bb9365/relation_extraction/stanford_tag_dataset.py#L28

I will add it to the ReadMe as well

Daniil

**Comment by daniilsorokin** [comment]
Added info on CoreNLP models in the ReadMe
